services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./source:/app
    command: sleep infinity