FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

# ef core
RUN dotnet tool install --global dotnet-ef

# sonar scanner
RUN dotnet tool install --global dotnet-sonarscanner

ENV PATH="$PATH:/root/.dotnet/tools"